# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2017-05-15 17:30
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='BalanceSheet',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('variable', models.CharField(max_length=255)),
                ('year', models.IntegerField()),
                ('value', models.CharField(max_length=255)),
            ],
            options={
                'db_table': 'balance_sheet',
            },
        ),
        migrations.AlterUniqueTogether(
            name='balancesheet',
            unique_together=set([('variable', 'year')]),
        ),
    ]
